admin/team.md
Resolves #[add the issue number associated with your pull request here]
Added my personal overview
=> added Gabriel's personal overview

admin/meetings/110321-sprint-1.md
=> sprint meeting note

admin/meetings/102721-team-goals.md, admin/meetings/110321-sprint-1.md
Pitch and sprint 1 planning meeting notes
=> Meeting notes

source/navbar.css, source/navbar.html
Resolves #20 
Here is a video showing the functionality of the navbar
https://user-images.githubusercontent.com/31702110/140909080-c0429891-84ba-4fb3-820b-8d273a08ac75.mp4
**UPDATE**: The tabs for the desktop (landscape) view are now left justified instead of centered like in the above video.
=> Created responsive navigation bar

admin/meetings/111021-sprint-1-check-in.md
=> format fixes

.github/workflows/lint.yml, .jshintrc
Resolves #39 
Sets up a JavaScript linting workflow on all pull requests. Also, removes linting workflows from running when pull requests are merged into `main`.
=> Setup JavaScript linting CI workflow

.github/workflows/lint.yml, source/cookbook.html
Resolves #62 
This changes the linting workflow so Prettier checks for correct formatting. Previously, the Prettier check was only formatting the files but not actually checking the formatting of the files in the PR.
=> Changed linting workflow so Prettier checks for correct formatting

.jshintrc
Changes a few problematic settings in JSHint that either conflict with Prettier or are unneeded for our project.
=> changed some problematic settings in .jshintrc

package.json
Resolves #93
Adds Jest and JSDoc scripts to npm
=> Added npm scripts for Jest and JSDoc

source/components/cook-book.js, source/components/cookbook-card.js, source/components/create-cookbook.js, source/components/explore-page.js, source/components/footer-img.js, source/components/home-page.js, source/components/navbar.js, source/components/notification-recipe-added.js, source/components/notification-recipe-deleted.js, source/components/notification-select-cookbook.js, source/components/recipe-card-delete.js, source/components/recipe-card.js, source/components/recipe-form.js, source/components/recipe-page.js, source/components/single-cookbook.js, source/index.html, source/scripts/app.js, source/styles/RCCdelstyle.css, source/styles/RCCstyle.css, source/styles/cook-book.css, source/styles/cookbook-card.css, source/styles/footer-img.css, source/styles/home-page.css, source/styles/navbar.css, source/styles/single-cookbook.css
Resolves #103 
There are a lot of modified files in this PR because I discovered several bugs as I was making the navbar functional. I also organized a lot of the mess in our files. Please just look at `source/scripts/app.js` to see the changes related to making the navbar functional.
Here is a video of the functional navbar
https://user-images.githubusercontent.com/31702110/141715027-d9bcdebe-0c3a-464a-9c24-dcae6fb292f0.mp4
=> Made navbar functional

source/scripts/app.js
Resolves #123 
Links the My Cookbooks page with Create New Cookbook page through the red plus button.
=> wired new cookbookButton to create newCookbookPage

source/index.html, source/scripts/app.js, source/styles/home-page.css
Resolves #105 
Here is a video of the homepage, I loaded 4 recipe cards instead of 3 so it looks better on mobile view.
https://user-images.githubusercontent.com/77420536/141946880-5b6013af-c9d2-452d-97d7-81c786b48d7c.mp4
=> Recipes homepage

admin/meetings/111621-weekly-meeting.md
Meeting notes from today's mentor meeting
=> 111621-weekly-meeting.md

source/scripts/app.js, source/styles/notification-select-cookbook.css
Resolves #130 and #131 
Sets up a click event listener for the edit/add to cookbook button in the recipe page, which navigates to the recipe form or opens the cookbook selector, respectively.
=> Set up recipe action button events

source/index.html, source/scripts/app.js, source/styles/create-cookbook.css
Resolves #132 
Added event listener to create new cookbook button. Also made minor changes to index.html to access inputs from the user.
=> Create cookbook functionality

source/scripts/app.js
=> Learn more

source/index.html, source/scripts/app.js
=> add recipe button

source/components/edit-cookbook.js, source/index.html, source/scripts/app.js, source/styles/cookbook-card.css, source/styles/edit-cookbook.css
Resolves #133
Binds an event listener to the "Save Changes" button in edit-cookbook-template.
The problem I am stuck on however, is how to get the original title of the cookbook to pass into the indexedDb.editCookbook() to update the cookbook.
=> Edit cookbook functionality

source/scripts/app.js
Resolves #113 
Added learn more event listener in explore page
=> Learn more explore

README.md, source/components/cook-book.js, source/components/cookbook-card.js, source/components/create-cookbook.js, source/components/edit-cookbook.js, source/components/explore-page.js, source/components/footer-img.js, source/components/home-page.js, source/components/navbar.js, source/components/notification-recipe-added.js, source/components/notification-recipe-deleted.js, source/components/notification-select-cookbook.js, source/components/recipe-card-delete.js, source/components/recipe-card.js, source/components/recipe-form.js, source/components/recipe-page.js, source/components/single-cookbook.js, source/index.html, source/scripts/spoonacular-interface.js, source/styles/explore-page.css, source/styles/home-page.css
Resolves #166 
Our web app will be hosted by Netlify from the `source` directory, therefore, we need to make all the directory URLs relative to the  `source` directory to allow Netlify to fetch the assets in `source` properly
=> Made all directory URLs relative to source directory to allow Netlify hosting from source directory

specs/adrs/netlify-decision.md
ADR to use Netlify for hosting instead of Heroku
=> Netlify ADR

source/index.html, source/scripts/app.js, source/styles/explore-page.css
Resolves #126 
Here is a video of the cuisine filter and time filter.
https://user-images.githubusercontent.com/77420536/142751314-07561abb-af5c-4e1b-8abe-cc38a167bce9.mp4
=> Cuisine filter

source/scripts/spoonacular-interface.js
Enables Spoonacular by default
=> Enabled spoonacular by default

source/scripts/app.js
Resolves #194 
Changed a textContent to innerHTML so that the HTML tags are automatically applied to the descriptions in the recipe page.
=> changed textcontent to innerhtml

source/scripts/app.js
=> implement home search

source/index.html, source/scripts/app.js, source/scripts/spoonacular-interface.js, source/styles/cook-book.css, source/styles/cookbook-card.css, source/styles/create-cookbook.css, source/styles/edit-cookbook.css, source/styles/explore-page.css, source/styles/home-page.css, source/styles/index.css, source/styles/navbar.css, source/styles/notification-recipe-added.css, source/styles/notification-recipe-deleted.css, source/styles/notification-select-cookbook.css, source/styles/recipe-card-delete.css, source/styles/recipe-card.css, source/styles/recipe-form.css, source/styles/recipe-page.css, source/styles/single-cookbook.css
Resolves #179 
Here is a video of the mobile view of the app. I removed the image from the home page so that you don't have to scroll down too much. I also moved the navbar to the top of the screen so that you don't have to scroll down to see it. 
https://user-images.githubusercontent.com/77420536/143385148-406086cf-7ea6-41b0-bae0-f0609d5407d3.mp4
=> fixed the UI for mobile view and add time filter

specs/adrs/filter-instant-update-decision.md
Resolves #202 
ADR added for instant update on filters
=> adr for instant update on filters added

source/index.html, source/scripts/app.js
=> edit cookbook fill params

.github/workflows/documentation.yml, .github/workflows/lint.yml, .github/workflows/test.yml, README.md, source/scripts/spoonacular-interface.js
Resolves #185
Set up a workflow to generate documentation with JSDoc on all merges into `main`
=> Jsdoc workflow

source/scripts/app.js, source/scripts/router.js, source/styles/cookbook-card.css
Resolves #167, resolves #206, resolves #207 
- Removed the ability to edit the default cookbook
- Populates the Select Cookbook options when cookbooks are added, edited, or deleted
- Closes the Select Cookbook popup when navigating to different pages
=> Minor bug fixes

source/index.html, source/styles/cook-book.css, source/styles/navbar.css, source/styles/single-cookbook.css
Resolves #174 
moved add button to center and bottom.
Here is a video showing the sticky buttons:
https://user-images.githubusercontent.com/31702110/144558840-b9b2fe3d-79a2-4917-992d-94edfd888b76.mp4
=> commit move add button

source/components/recipe-page.js, source/index.html, source/scripts/app.js, source/styles/recipe-page.css
Resolves #226 
Refactored the recipe page to contain functions for populating the recipe page and for scaling the ingredient amounts on the recipe page
Here is a demonstration of the new function which allows scaling of the original ingredient amounts
https://user-images.githubusercontent.com/31702110/144697976-f2552025-7cfe-4e10-8941-7bd5bf0b6017.mp4
=> Recipe Page Refactor

source/components/recipe-page.js, source/components/tests/recipe-page.test.js
Resolves #228 
Adds non-trivial tests for the `populateRecipePage` and `scaleIngredientAmounts` functions in the `recipe-page` custom element
=> added non-trivial tests for recipe-page custom element
